//MC68HC908JK8 Register Memory Map Script
//Creates labels for all I/O registers from $0000-$003F plus system registers from $FE00-$FFFF
//All registers are prefixed with REG_ for easy identification
//Reference: MC68HC908JL8/JK8 Data Sheet, Rev. 3.1 - Figure 2-2
//@author Generated by claude.ia from hc08reg.pdf
//@category HC08
//@keybinding
//@menupath
//@toolbar

import ghidra.app.script.GhidraScript;
import ghidra.program.model.address.Address;
import ghidra.program.model.symbol.SourceType;
import ghidra.program.model.symbol.Symbol;
import ghidra.program.model.symbol.SymbolTable;
import ghidra.program.model.data.*;

public class HC08_RegisterMap extends GhidraScript {

	private DataTypeManager dtm;
	private SymbolTable symbolTable;

	@Override
	public void run() throws Exception {
		dtm = currentProgram.getDataTypeManager();
		symbolTable = currentProgram.getSymbolTable();

		println("MC68HC908JK8 Register Memory Map Script");
		println("========================================");

		createPortRegisters();
		createSCIRegisters();
		createKeyboardRegisters();
		createSystemRegisters();
		createTimerRegisters();
		createADCRegisters();
		createBreakRegisters();
		createFlashRegisters();
		createCOPRegister();

		println("HC08 register mapping complete!");
	}

	private void createRegLabel(long address, String name, int size) throws Exception {
		Address addr = toAddr(address);
		String regName = "REG_" + name;

		// Remove any existing labels at this address
		Symbol[] existingSymbols = symbolTable.getSymbols(addr);
		for (Symbol sym : existingSymbols) {
			if (!sym.isPrimary() || sym.getSource() != SourceType.DEFAULT) {
				sym.delete();
			}
		}

		// Create the new label with REG_ prefix
		createLabel(addr, regName, true);

		// Apply appropriate data type based on size (using stdint types)
		String typeName = null;
		switch (size) {
			case 1: typeName = "/byte"; break;
			case 2: typeName = "/ushort"; break;
			case 4: typeName = "/uint"; break;
		}

		if (typeName != null) {
			DataType dt = dtm.getDataType(typeName);
			if (dt != null) {
				clearListing(addr, addr.add(size - 1));
				createData(addr, dt);
			}
		}
	}

	private void createPortRegisters() throws Exception {
		println("Creating Port I/O registers...");

		// Port data registers
		createRegLabel(0x0000L, "PTA", 1); // Port A Data Register
		createRegLabel(0x0001L, "PTB", 1); // Port B Data Register
		// 0x0002 unimplemented
		createRegLabel(0x0003L, "PTD", 1); // Port D Data Register

		// Data direction registers
		createRegLabel(0x0004L, "DDRA", 1); // Data Direction Register A
		createRegLabel(0x0005L, "DDRB", 1); // Data Direction Register B
		// 0x0006 unimplemented
		createRegLabel(0x0007L, "DDRD", 1); // Data Direction Register D

		// Port E
		createRegLabel(0x0008L, "PTE", 1); // Port E Data Register (PTE1:PTE0)
		// 0x0009 unimplemented

		// Port D control
		createRegLabel(0x000AL, "PDCR", 1); // Port D Control Register (slew/pullup)
		// 0x000B unimplemented

		// Port E direction
		createRegLabel(0x000CL, "DDRE", 1); // Data Direction Register E

		// Port A pull-up enable
		createRegLabel(0x000DL, "PTAPUE", 1); // Port A Input Pull-up Enable Register
		createRegLabel(0x000EL, "PTA7PUE", 1); // PTA7 Input Pull-up Enable Register
		// 0x000F-0x0012 unimplemented
	}

	private void createSCIRegisters() throws Exception {
		println("Creating SCI (Serial Communications Interface) registers...");

		createRegLabel(0x0013L, "SCC1", 1); // SCI Control Register 1
		createRegLabel(0x0014L, "SCC2", 1); // SCI Control Register 2
		createRegLabel(0x0015L, "SCC3", 1); // SCI Control Register 3
		createRegLabel(0x0016L, "SCS1", 1); // SCI Status Register 1
		createRegLabel(0x0017L, "SCS2", 1); // SCI Status Register 2
		createRegLabel(0x0018L, "SCDR", 1); // SCI Data Register
		createRegLabel(0x0019L, "SCBR", 1); // SCI Baud Rate Register
	}

	private void createKeyboardRegisters() throws Exception {
		println("Creating Keyboard registers...");

		createRegLabel(0x001AL, "KBSCR", 1); // Keyboard Status and Control Register
		createRegLabel(0x001BL, "KBIER", 1); // Keyboard Interrupt Enable Register
		// 0x001C unimplemented
	}

	private void createSystemRegisters() throws Exception {
		println("Creating System Control registers...");

		createRegLabel(0x001DL, "INTSCR", 1); // IRQ Status and Control Register
		createRegLabel(0x001EL, "CONFIG2", 1); // Configuration Register 2
		createRegLabel(0x001FL, "CONFIG1", 1); // Configuration Register 1
	}

	private void createTimerRegisters() throws Exception {
		println("Creating Timer registers...");

		// TIM1 - Timer 1
		createRegLabel(0x0020L, "T1SC", 1); // TIM1 Status and Control Register
		createRegLabel(0x0021L, "T1CNTH", 1); // TIM1 Counter Register High
		createRegLabel(0x0022L, "T1CNTL", 1); // TIM1 Counter Register Low
		createRegLabel(0x0023L, "T1MODH", 1); // TIM1 Counter Modulo Register High
		createRegLabel(0x0024L, "T1MODL", 1); // TIM1 Counter Modulo Register Low

		// TIM1 Channel 0
		createRegLabel(0x0025L, "T1SC0", 1); // TIM1 Channel 0 Status and Control Register
		createRegLabel(0x0026L, "T1CH0H", 1); // TIM1 Channel 0 Register High
		createRegLabel(0x0027L, "T1CH0L", 1); // TIM1 Channel 0 Register Low

		// TIM1 Channel 1
		createRegLabel(0x0028L, "T1SC1", 1); // TIM1 Channel 1 Status and Control Register
		createRegLabel(0x0029L, "T1CH1H", 1); // TIM1 Channel 1 Register High
		createRegLabel(0x002AL, "T1CH1L", 1); // TIM1 Channel 1 Register Low
		// 0x002B-0x002F unimplemented

		// TIM2 - Timer 2
		createRegLabel(0x0030L, "T2SC", 1); // TIM2 Status and Control Register
		createRegLabel(0x0031L, "T2CNTH", 1); // TIM2 Counter Register High
		createRegLabel(0x0032L, "T2CNTL", 1); // TIM2 Counter Register Low
		createRegLabel(0x0033L, "T2MODH", 1); // TIM2 Counter Modulo Register High
		createRegLabel(0x0034L, "T2MODL", 1); // TIM2 Counter Modulo Register Low

		// TIM2 Channel 0
		createRegLabel(0x0035L, "T2SC0", 1); // TIM2 Channel 0 Status and Control Register
		createRegLabel(0x0036L, "T2CH0H", 1); // TIM2 Channel 0 Register High
		createRegLabel(0x0037L, "T2CH0L", 1); // TIM2 Channel 0 Register Low

		// TIM2 Channel 1
		createRegLabel(0x0038L, "T2SC1", 1); // TIM2 Channel 1 Status and Control Register
		createRegLabel(0x0039L, "T2CH1H", 1); // TIM2 Channel 1 Register High
		createRegLabel(0x003AL, "T2CH1L", 1); // TIM2 Channel 1 Register Low
		// 0x003B unimplemented
	}

	private void createADCRegisters() throws Exception {
		println("Creating ADC registers...");

		createRegLabel(0x003CL, "ADSCR", 1); // ADC Status and Control Register
		createRegLabel(0x003DL, "ADR", 1); // ADC Data Register
		createRegLabel(0x003EL, "ADICLK", 1); // ADC Input Clock Register
		// 0x003F unimplemented
	}

	private void createBreakRegisters() throws Exception {
		println("Creating Break and System registers ($FExx)...");

		createRegLabel(0xFE00L, "BSR", 1); // Break Status Register
		createRegLabel(0xFE01L, "RSR", 1); // Reset Status Register
		// 0xFE02 reserved
		createRegLabel(0xFE03L, "BFCR", 1); // Break Flag Control Register
		createRegLabel(0xFE04L, "INT1", 1); // Interrupt Status Register 1
		createRegLabel(0xFE05L, "INT2", 1); // Interrupt Status Register 2
		createRegLabel(0xFE06L, "INT3", 1); // Interrupt Status Register 3
		// 0xFE07 reserved
		createRegLabel(0xFE08L, "FLCR", 1); // Flash Control Register
		// 0xFE09-0xFE0B reserved
		createRegLabel(0xFE0CL, "BRKH", 1); // Break Address High Register
		createRegLabel(0xFE0DL, "BRKL", 1); // Break Address Low Register
		createRegLabel(0xFE0EL, "BRKSCR", 1); // Break Status and Control Register
		// 0xFE0F reserved
	}

	private void createFlashRegisters() throws Exception {
		println("Creating Flash and Option registers...");

		createRegLabel(0xFFCFL, "FLBPR", 1); // Flash Block Protect Register
		createRegLabel(0xFFD0L, "MOR", 1); // Mask Option Register
	}

	private void createCOPRegister() throws Exception {
		println("Creating COP register...");

		createRegLabel(0xFFFFL, "COPCTL", 1); // COP Control Register
	}
}
