//MPC5534 Register Memory Map Script
//Creates labels for all internal registers from Appendix A of the Reference Manual
//All registers are prefixed with REG_ for easy identification
//@author Generated by claude.ai from MPC5534RM.pdf
//@category MPC55xx
//@keybinding
//@menupath
//@toolbar

import ghidra.app.script.GhidraScript;
import ghidra.program.model.address.Address;
import ghidra.program.model.symbol.SourceType;
import ghidra.program.model.symbol.Symbol;
import ghidra.program.model.symbol.SymbolTable;
import ghidra.program.model.data.*;

public class MPC5534_RegisterMap extends GhidraScript {

	private DataTypeManager dtm;
	private SymbolTable symbolTable;

	// Module base addresses
	private static final long FMPLL_BASE     = 0xC3F80000L;
	private static final long EBI_BASE       = 0xC3F84000L;
	private static final long FLASH_BASE     = 0xC3F88000L;
	private static final long SIU_BASE       = 0xC3F90000L;
	private static final long EMIOS_BASE     = 0xC3FA0000L;
	private static final long ETPU_BASE      = 0xC3FC0000L;
	private static final long XBAR_BASE      = 0xFFF04000L;
	private static final long ECSM_BASE      = 0xFFF40000L;
	private static final long EDMA_BASE      = 0xFFF44000L;
	private static final long INTC_BASE      = 0xFFF48000L;
	private static final long EQADC_BASE     = 0xFFF80000L;
	private static final long DSPI_B_BASE    = 0xFFF94000L;
	private static final long DSPI_C_BASE    = 0xFFF98000L;
	private static final long DSPI_D_BASE    = 0xFFF9C000L;
	private static final long ESCI_A_BASE    = 0xFFFB0000L;
	private static final long ESCI_B_BASE    = 0xFFFB4000L;
	private static final long FLEXCAN_A_BASE = 0xFFFC0000L;
	private static final long FLEXCAN_C_BASE = 0xFFFC8000L;

	@Override
	public void run() throws Exception {
		dtm = currentProgram.getDataTypeManager();
		symbolTable = currentProgram.getSymbolTable();

		println("MPC5534 Register Memory Map Script");
		println("===================================");

		createFMPLLRegisters();
		createEBIRegisters();
		createFlashRegisters();
		createSIURegisters();
		createEMIOSRegisters();
		createETPURegisters();
		createXBARRegisters();
		createECSMRegisters();
		createEDMARegisters();
		createINTCRegisters();
		createEQADCRegisters();
		createDSPIRegisters(DSPI_B_BASE, "B");
		createDSPIRegisters(DSPI_C_BASE, "C");
		createDSPIRegisters(DSPI_D_BASE, "D");
		createESCIRegisters(ESCI_A_BASE, "A");
		createESCIRegisters(ESCI_B_BASE, "B");
		createFlexCANRegisters(FLEXCAN_A_BASE, "A");
		createFlexCANRegisters(FLEXCAN_C_BASE, "C");

		println("Register mapping complete!");
	}

	private void createRegLabel(long address, String name, int size) throws Exception {
		Address addr = toAddr(address);
		String regName = "REG_" + name;

		// Remove any existing labels at this address
		Symbol[] existingSymbols = symbolTable.getSymbols(addr);
		for (Symbol sym : existingSymbols) {
			if (!sym.isPrimary() || sym.getSource() != SourceType.DEFAULT) {
				sym.delete();
			}
		}

		// Create the new label with REG_ prefix
		createLabel(addr, regName, true);

		// Apply appropriate data type based on size
		String typeName = null;
		switch (size) {
			case 1: typeName = "/byte"; break;
			case 2: typeName = "/ushort"; break;
			case 4: typeName = "/uint"; break;
		}

		if (typeName != null) {
			DataType dt = dtm.getDataType(typeName);
			if (dt != null) {
				clearListing(addr, addr.add(size - 1));
				createData(addr, dt);
			}
		}
	}

	private void createFMPLLRegisters() throws Exception {
		println("Creating FMPLL registers...");
		createRegLabel(FMPLL_BASE + 0x0000L, "FMPLL_SYNCR", 4);
		createRegLabel(FMPLL_BASE + 0x0004L, "FMPLL_SYNSR", 4);
	}

	private void createEBIRegisters() throws Exception {
		println("Creating EBI registers...");
		createRegLabel(EBI_BASE + 0x0000L, "EBI_MCR",      4);
		createRegLabel(EBI_BASE + 0x0008L, "EBI_TESR",     4);
		createRegLabel(EBI_BASE + 0x000CL, "EBI_BMCR",     4);
		// Base/Option registers for banks 0-3
		createRegLabel(EBI_BASE + 0x0010L, "EBI_BR0",      4);
		createRegLabel(EBI_BASE + 0x0014L, "EBI_OR0",      4);
		createRegLabel(EBI_BASE + 0x0018L, "EBI_BR1",      4);
		createRegLabel(EBI_BASE + 0x001CL, "EBI_OR1",      4);
		createRegLabel(EBI_BASE + 0x0020L, "EBI_BR2",      4);
		createRegLabel(EBI_BASE + 0x0024L, "EBI_OR2",      4);
		createRegLabel(EBI_BASE + 0x0028L, "EBI_BR3",      4);
		createRegLabel(EBI_BASE + 0x002CL, "EBI_OR3",      4);
		// Calibration Base/Option registers for banks 0-3
		createRegLabel(EBI_BASE + 0x0040L, "EBI_CAL_BR0",  4);
		createRegLabel(EBI_BASE + 0x0044L, "EBI_CAL_OR0",  4);
		createRegLabel(EBI_BASE + 0x0048L, "EBI_CAL_BR1",  4);
		createRegLabel(EBI_BASE + 0x004CL, "EBI_CAL_OR1",  4);
		createRegLabel(EBI_BASE + 0x0050L, "EBI_CAL_BR2",  4);
		createRegLabel(EBI_BASE + 0x0054L, "EBI_CAL_OR2",  4);
		createRegLabel(EBI_BASE + 0x0058L, "EBI_CAL_BR3",  4);
		createRegLabel(EBI_BASE + 0x005CL, "EBI_CAL_OR3",  4);
	}

	private void createFlashRegisters() throws Exception {
		println("Creating Flash Control registers...");
		createRegLabel(FLASH_BASE + 0x0000L, "FLASH_MCR",    4);
		createRegLabel(FLASH_BASE + 0x0004L, "FLASH_LMLR",   4);
		createRegLabel(FLASH_BASE + 0x0008L, "FLASH_HLR",    4);
		createRegLabel(FLASH_BASE + 0x000CL, "FLASH_SLMLR",  4);
		createRegLabel(FLASH_BASE + 0x0010L, "FLASH_LMSR",   4);
		createRegLabel(FLASH_BASE + 0x0014L, "FLASH_HSR",    4);
		createRegLabel(FLASH_BASE + 0x0018L, "FLASH_AR",     4);
		createRegLabel(FLASH_BASE + 0x001CL, "FLASH_BIUCR",  4);
		createRegLabel(FLASH_BASE + 0x0020L, "FLASH_BIUAPR", 4);
		createRegLabel(FLASH_BASE + 0x0024L, "FLASH_BIUCR2", 4);
	}

	private void createSIURegisters() throws Exception {
		println("Creating SIU registers...");

		// SIU base registers
		createRegLabel(SIU_BASE + 0x0000L, "SIU_MIDR",  4);
		createRegLabel(SIU_BASE + 0x000CL, "SIU_RSR",   4);
		createRegLabel(SIU_BASE + 0x0010L, "SIU_SRCR",  4);
		createRegLabel(SIU_BASE + 0x0014L, "SIU_EISR",  4);
		createRegLabel(SIU_BASE + 0x0018L, "SIU_DIRER", 4);
		createRegLabel(SIU_BASE + 0x001CL, "SIU_DIRSR", 4);
		createRegLabel(SIU_BASE + 0x0020L, "SIU_OSR",   4);
		createRegLabel(SIU_BASE + 0x0024L, "SIU_ORER",  4);
		createRegLabel(SIU_BASE + 0x0028L, "SIU_IREER", 4);
		createRegLabel(SIU_BASE + 0x002CL, "SIU_IFEER", 4);
		createRegLabel(SIU_BASE + 0x0030L, "SIU_IDFR",  4);

		// PCR - Pad Configuration Registers (16-bit), at SIU_BASE + 0x0040 + n*2
		// Valid pad indices per reference manual
		int[][] pcrRanges = {
			{0, 4}, {8, 44}, {62, 66}, {68, 71}, {75, 111},
			{113, 135}, {142, 146}, {179, 205}, {206, 231}
		};
		int[] pcrIndividual = {336, 338, 339, 340, 341, 342};

		for (int[] range : pcrRanges) {
			for (int n = range[0]; n < range[1]; n++) {
				createRegLabel(SIU_BASE + 0x0040L + n * 2, "SIU_PCR" + n, 2);
			}
		}
		for (int n : pcrIndividual) {
			createRegLabel(SIU_BASE + 0x0040L + n * 2, "SIU_PCR" + n, 2);
		}

		// GPDO - GPIO Pin Data Output Registers (8-bit), at SIU_BASE + 0x0600 + n
		int[][] gpioRanges = {
			{0, 4}, {8, 44}, {62, 66}, {68, 71}, {74, 111},
			{113, 205}, {206, 214}
		};
		for (int[] range : gpioRanges) {
			for (int n = range[0]; n < range[1]; n++) {
				createRegLabel(SIU_BASE + 0x0600L + n, "SIU_GPDO" + n, 1);
			}
		}

		// GPDI - GPIO Pin Data Input Registers (8-bit), at SIU_BASE + 0x0800 + n
		for (int[] range : gpioRanges) {
			for (int n = range[0]; n < range[1]; n++) {
				createRegLabel(SIU_BASE + 0x0800L + n, "SIU_GPDI" + n, 1);
			}
		}

		// External interrupt / DMA routing registers
		createRegLabel(SIU_BASE + 0x0900L, "SIU_ETISR", 4);
		createRegLabel(SIU_BASE + 0x0904L, "SIU_EIISR", 4);
		createRegLabel(SIU_BASE + 0x0908L, "SIU_DISR",  4);
		createRegLabel(SIU_BASE + 0x0980L, "SIU_CCR",   4);
		createRegLabel(SIU_BASE + 0x0984L, "SIU_ECCR",  4);
		createRegLabel(SIU_BASE + 0x0988L, "SIU_CARH",  4);
		createRegLabel(SIU_BASE + 0x098CL, "SIU_CARL",  4);
		createRegLabel(SIU_BASE + 0x0990L, "SIU_CBRH",  4);
		createRegLabel(SIU_BASE + 0x0994L, "SIU_CBRL",  4);
	}

	private void createEMIOSRegisters() throws Exception {
		println("Creating eMIOS registers...");

		// Global registers
		createRegLabel(EMIOS_BASE + 0x0000L, "EMIOS_MCR",  4);
		createRegLabel(EMIOS_BASE + 0x0004L, "EMIOS_GFR",  4);
		createRegLabel(EMIOS_BASE + 0x0008L, "EMIOS_OUDR", 4);

		// Per-channel registers: channels 0..23, at EMIOS_BASE + 0x0020*(n+1)
		for (int n = 0; n < 24; n++) {
			long base = EMIOS_BASE + 0x0020L * (n + 1);
			createRegLabel(base + 0x00L, "EMIOS_UC" + n + "_CADR",  4);
			createRegLabel(base + 0x04L, "EMIOS_UC" + n + "_CBDR",  4);
			createRegLabel(base + 0x08L, "EMIOS_UC" + n + "_CCNTR", 4);
			createRegLabel(base + 0x0CL, "EMIOS_UC" + n + "_CCR",   4);
			createRegLabel(base + 0x10L, "EMIOS_UC" + n + "_CSR",   4);
		}
	}

	private void createETPURegisters() throws Exception {
		println("Creating eTPU registers...");

		// Global / shared registers
		createRegLabel(ETPU_BASE + 0x0000L, "ETPU_MCR",         4);
		createRegLabel(ETPU_BASE + 0x0004L, "ETPU_CDCR",        4);
		createRegLabel(ETPU_BASE + 0x000CL, "ETPU_MISCCMPR",    4);
		createRegLabel(ETPU_BASE + 0x0010L, "ETPU_SCMOFFDATAR", 4);

		// Engine A registers
		createRegLabel(ETPU_BASE + 0x0014L, "ETPU_ECR_A",     4);
		createRegLabel(ETPU_BASE + 0x0020L, "ETPU_TBCR_A",    4);
		createRegLabel(ETPU_BASE + 0x0024L, "ETPU_TB1R_A",    4);
		createRegLabel(ETPU_BASE + 0x0028L, "ETPU_TB2R_A",    4);
		createRegLabel(ETPU_BASE + 0x002CL, "ETPU_REDCR_A",   4);
		createRegLabel(ETPU_BASE + 0x0200L, "ETPU_CISR_A",    4);
		createRegLabel(ETPU_BASE + 0x0210L, "ETPU_CDTRSR_A",  4);
		createRegLabel(ETPU_BASE + 0x0220L, "ETPU_CIOSR_A",   4);
		createRegLabel(ETPU_BASE + 0x0230L, "ETPU_CDTROSR_A", 4);
		createRegLabel(ETPU_BASE + 0x0240L, "ETPU_CIER_A",    4);
		createRegLabel(ETPU_BASE + 0x0250L, "ETPU_CDTRER_A",  4);
		createRegLabel(ETPU_BASE + 0x0280L, "ETPU_CPSSR_A",   4);
		createRegLabel(ETPU_BASE + 0x0290L, "ETPU_CSSR_A",    4);

		// Per-channel registers: channels 0..31, at ETPU_BASE + 0x0400 + ch*0x10
		for (int ch = 0; ch < 32; ch++) {
			long base = ETPU_BASE + 0x0400L + ch * 0x10L;
			createRegLabel(base + 0x00L, "ETPU_C" + ch + "CR_A",   4);
			createRegLabel(base + 0x04L, "ETPU_C" + ch + "SCR_A",  4);
			createRegLabel(base + 0x08L, "ETPU_C" + ch + "HSRR_A", 4);
		}

		// Shared Data Memory and Shared Code Memory start labels
		createRegLabel(ETPU_BASE + 0x8000L,  "ETPU_SDM", 0x0C00);
		createRegLabel(ETPU_BASE + 0x10000L, "ETPU_SCM", 0x3000);
	}

	private void createXBARRegisters() throws Exception {
		println("Creating XBAR registers...");
		createRegLabel(XBAR_BASE + 0x0000L, "XBAR_MPR0",   4);
		createRegLabel(XBAR_BASE + 0x0010L, "XBAR_SGPCR0", 4);
		createRegLabel(XBAR_BASE + 0x0100L, "XBAR_MPR1",   4);
		createRegLabel(XBAR_BASE + 0x0110L, "XBAR_SGPCR1", 4);
		createRegLabel(XBAR_BASE + 0x0300L, "XBAR_MPR3",   4);
		createRegLabel(XBAR_BASE + 0x0310L, "XBAR_SGPCR3", 4);
		createRegLabel(XBAR_BASE + 0x0600L, "XBAR_MPR6",   4);
		createRegLabel(XBAR_BASE + 0x0610L, "XBAR_SGPCR6", 4);
		createRegLabel(XBAR_BASE + 0x0700L, "XBAR_MPR7",   4);
		createRegLabel(XBAR_BASE + 0x0710L, "XBAR_SGPCR7", 4);
	}

	private void createECSMRegisters() throws Exception {
		println("Creating ECSM registers...");
		createRegLabel(ECSM_BASE + 0x0016L, "ECSM_SWTCR",  2);
		createRegLabel(ECSM_BASE + 0x001BL, "ECSM_SWTSR",  1);
		createRegLabel(ECSM_BASE + 0x001FL, "ECSM_SWTIR",  1);
		createRegLabel(ECSM_BASE + 0x0043L, "ECSM_ECR",    1);
		createRegLabel(ECSM_BASE + 0x0047L, "ECSM_ESR",    1);
		createRegLabel(ECSM_BASE + 0x004AL, "ECSM_EEGR",   2);
		createRegLabel(ECSM_BASE + 0x0050L, "ECSM_FEAR",   4);
		createRegLabel(ECSM_BASE + 0x0056L, "ECSM_FEMR",   1);
		createRegLabel(ECSM_BASE + 0x0057L, "ECSM_FEAT",   1);
		createRegLabel(ECSM_BASE + 0x0058L, "ECSM_FEDRH",  4);
		createRegLabel(ECSM_BASE + 0x005CL, "ECSM_FEDRL",  4);
		createRegLabel(ECSM_BASE + 0x0060L, "ECSM_REAR",   4);
		createRegLabel(ECSM_BASE + 0x0066L, "ECSM_REMR",   1);
		createRegLabel(ECSM_BASE + 0x0067L, "ECSM_REAT",   1);
		createRegLabel(ECSM_BASE + 0x0068L, "ECSM_REDRH",  4);
		createRegLabel(ECSM_BASE + 0x006CL, "ECSM_REDRL",  4);
	}

	private void createEDMARegisters() throws Exception {
		println("Creating eDMA registers...");

		createRegLabel(EDMA_BASE + 0x0000L, "EDMA_CR",    4);
		createRegLabel(EDMA_BASE + 0x0004L, "EDMA_ESR",   4);
		createRegLabel(EDMA_BASE + 0x000CL, "EDMA_ERQRL", 4);
		createRegLabel(EDMA_BASE + 0x0014L, "EDMA_EEIRL", 4);
		createRegLabel(EDMA_BASE + 0x0018L, "EDMA_SERQR", 1);
		createRegLabel(EDMA_BASE + 0x0019L, "EDMA_CERQR", 1);
		createRegLabel(EDMA_BASE + 0x001AL, "EDMA_SEEIR", 1);
		createRegLabel(EDMA_BASE + 0x001BL, "EDMA_CEEIR", 1);
		createRegLabel(EDMA_BASE + 0x001CL, "EDMA_CIRQR", 1);
		createRegLabel(EDMA_BASE + 0x001DL, "EDMA_CER",   1);
		createRegLabel(EDMA_BASE + 0x001EL, "EDMA_SSBR",  1);
		createRegLabel(EDMA_BASE + 0x001FL, "EDMA_CDSBR", 1);
		createRegLabel(EDMA_BASE + 0x0024L, "EDMA_IRQRL", 4);
		createRegLabel(EDMA_BASE + 0x002CL, "EDMA_ERL",   4);

		// Channel Priority Registers (8-bit each)
		for (int n = 0; n < 32; n++) {
			createRegLabel(EDMA_BASE + 0x0100L + n, "EDMA_CPR" + n, 1);
		}

		// Transfer Control Descriptors: TCD0-31, 32 bytes each
		for (int n = 0; n < 32; n++) {
			createRegLabel(EDMA_BASE + 0x1000L + n * 0x20L, "EDMA_TCD" + n, 32);
		}
	}

	private void createINTCRegisters() throws Exception {
		println("Creating INTC registers...");

		createRegLabel(INTC_BASE + 0x0000L, "INTC_MCR",   4);
		createRegLabel(INTC_BASE + 0x0008L, "INTC_CPR",   4);
		createRegLabel(INTC_BASE + 0x0010L, "INTC_IACKR", 4);
		createRegLabel(INTC_BASE + 0x0018L, "INTC_EOIR",  4);

		// Software Set/Clear Interrupt Registers (8-bit)
		for (int n = 0; n < 8; n++) {
			createRegLabel(INTC_BASE + 0x0020L + n, "INTC_SSCIR" + n, 1);
		}

		// Priority Select Registers (8-bit): PSR0-211
		for (int n = 0; n < 212; n++) {
			createRegLabel(INTC_BASE + 0x0040L + n, "INTC_PSR" + n, 1);
		}
	}

	private void createEQADCRegisters() throws Exception {
		println("Creating eQADC registers...");

		createRegLabel(EQADC_BASE + 0x0000L, "EQADC_MCR",    4);
		createRegLabel(EQADC_BASE + 0x0008L, "EQADC_NMSFR",  4);
		createRegLabel(EQADC_BASE + 0x000CL, "EQADC_ETDFR",  4);

		// Command FIFO Push Registers
		for (int n = 0; n < 6; n++) {
			createRegLabel(EQADC_BASE + 0x0010L + n * 4, "EQADC_CFPR" + n, 4);
		}

		// Result FIFO Pop Registers
		for (int n = 0; n < 6; n++) {
			createRegLabel(EQADC_BASE + 0x0030L + n * 4, "EQADC_RFPR" + n, 4);
		}

		// Command FIFO Control Registers (16-bit)
		for (int n = 0; n < 6; n++) {
			createRegLabel(EQADC_BASE + 0x0050L + n * 2, "EQADC_CFCR" + n, 2);
		}

		// Interrupt/DMA Control Registers (16-bit)
		for (int n = 0; n < 6; n++) {
			createRegLabel(EQADC_BASE + 0x0060L + n * 2, "EQADC_IDCR" + n, 2);
		}

		// FIFO and Scan Status Registers
		for (int n = 0; n < 6; n++) {
			createRegLabel(EQADC_BASE + 0x0070L + n * 4, "EQADC_FISR" + n, 4);
		}

		// Command FIFO Transfer Counter Registers (16-bit)
		for (int n = 0; n < 6; n++) {
			createRegLabel(EQADC_BASE + 0x0090L + n * 2, "EQADC_CFTCR" + n, 2);
		}

		// Command FIFO Status Snapshot Registers
		for (int n = 0; n < 3; n++) {
			createRegLabel(EQADC_BASE + 0x00A0L + n * 4, "EQADC_CFSSR" + n, 4);
		}

		createRegLabel(EQADC_BASE + 0x00ACL, "EQADC_CFSR",   4);
		createRegLabel(EQADC_BASE + 0x00B4L, "EQADC_SSICR",  4);
		createRegLabel(EQADC_BASE + 0x00B8L, "EQADC_SSIRDR", 4);

		// Command FIFO entries: CF0-5, 4 entries each
		long[] cfBases = {0x100L, 0x140L, 0x180L, 0x1C0L, 0x200L, 0x240L};
		for (int f = 0; f < 6; f++) {
			for (int e = 0; e < 4; e++) {
				createRegLabel(EQADC_BASE + cfBases[f] + e * 4, "EQADC_CF" + f + "_" + e, 4);
			}
		}

		// Result FIFO entries: RF0-5, 4 entries each
		long[] rfBases = {0x300L, 0x340L, 0x380L, 0x3C0L, 0x400L, 0x440L};
		for (int f = 0; f < 6; f++) {
			for (int e = 0; e < 4; e++) {
				createRegLabel(EQADC_BASE + rfBases[f] + e * 4, "EQADC_RF" + f + "_" + e, 4);
			}
		}
	}

	private void createDSPIRegisters(long base, String id) throws Exception {
		println("Creating DSPI_" + id + " registers...");
		createRegLabel(base + 0x0000L, "DSPI_" + id + "_MCR",   4);
		createRegLabel(base + 0x0008L, "DSPI_" + id + "_TCR",   4);
		// Clock and Transfer Attributes Registers
		for (int n = 0; n < 8; n++) {
			createRegLabel(base + 0x000CL + n * 4, "DSPI_" + id + "_CTAR" + n, 4);
		}
		createRegLabel(base + 0x002CL, "DSPI_" + id + "_SR",    4);
		createRegLabel(base + 0x0030L, "DSPI_" + id + "_RSER",  4);
		createRegLabel(base + 0x0034L, "DSPI_" + id + "_PUSHR", 4);
		createRegLabel(base + 0x0038L, "DSPI_" + id + "_POPR",  4);
		// TX FIFO Registers
		for (int n = 0; n < 4; n++) {
			createRegLabel(base + 0x003CL + n * 4, "DSPI_" + id + "_TXFR" + n, 4);
		}
		// RX FIFO Registers
		for (int n = 0; n < 4; n++) {
			createRegLabel(base + 0x007CL + n * 4, "DSPI_" + id + "_RXFR" + n, 4);
		}
		// DSI Configuration Registers
		createRegLabel(base + 0x00BCL, "DSPI_" + id + "_DSICR", 4);
		createRegLabel(base + 0x00C0L, "DSPI_" + id + "_SDR",   4);
		createRegLabel(base + 0x00C4L, "DSPI_" + id + "_ASDR",  4);
		createRegLabel(base + 0x00C8L, "DSPI_" + id + "_COMPR", 4);
		createRegLabel(base + 0x00CCL, "DSPI_" + id + "_DDR",   4);
	}

	private void createESCIRegisters(long base, String id) throws Exception {
		println("Creating eSCI_" + id + " registers...");
		createRegLabel(base + 0x0000L, "ESCI_" + id + "_CR1", 4);
		createRegLabel(base + 0x0004L, "ESCI_" + id + "_CR2", 2);
		createRegLabel(base + 0x0006L, "ESCI_" + id + "_DR",  2);
		createRegLabel(base + 0x0008L, "ESCI_" + id + "_SR",  4);
		createRegLabel(base + 0x000CL, "ESCI_" + id + "_LCR", 4);
		createRegLabel(base + 0x0010L, "ESCI_" + id + "_LTR", 4);
		createRegLabel(base + 0x0014L, "ESCI_" + id + "_LRR", 4);
		createRegLabel(base + 0x0018L, "ESCI_" + id + "_LPR", 4);
	}

	private void createFlexCANRegisters(long base, String id) throws Exception {
		println("Creating FlexCAN_" + id + " registers...");
		createRegLabel(base + 0x0000L, "FLEXCAN_" + id + "_MCR",      4);
		createRegLabel(base + 0x0004L, "FLEXCAN_" + id + "_CR",       4);
		createRegLabel(base + 0x0008L, "FLEXCAN_" + id + "_TIMER",    4);
		createRegLabel(base + 0x0010L, "FLEXCAN_" + id + "_RXGMASK",  4);
		createRegLabel(base + 0x0014L, "FLEXCAN_" + id + "_RX14MASK", 4);
		createRegLabel(base + 0x0018L, "FLEXCAN_" + id + "_RX15MASK", 4);
		createRegLabel(base + 0x001CL, "FLEXCAN_" + id + "_ECR",      4);
		createRegLabel(base + 0x0020L, "FLEXCAN_" + id + "_ESR",      4);
		createRegLabel(base + 0x0024L, "FLEXCAN_" + id + "_IMRH",     4);
		createRegLabel(base + 0x0028L, "FLEXCAN_" + id + "_IMRL",     4);
		createRegLabel(base + 0x002CL, "FLEXCAN_" + id + "_IFRH",     4);
		createRegLabel(base + 0x0030L, "FLEXCAN_" + id + "_IFRL",     4);

		// Message Buffers 0-63, 16 bytes each
		for (int buf = 0; buf < 64; buf++) {
			long mb = base + 0x0080L + buf * 0x10L;
			createRegLabel(mb + 0x00L, "FLEXCAN_" + id + "_MB" + buf + "_CS",    4);
			createRegLabel(mb + 0x04L, "FLEXCAN_" + id + "_MB" + buf + "_ID",    4);
			createRegLabel(mb + 0x08L, "FLEXCAN_" + id + "_MB" + buf + "_DATA0", 4);
			createRegLabel(mb + 0x0CL, "FLEXCAN_" + id + "_MB" + buf + "_DATA1", 4);
		}
	}
}
