//MPC561/MPC563 Register Memory Map Script
//Creates labels for all internal registers from Appendix B of the Reference Manual
//All registers are prefixed with REG_ for easy identification
//@author Generated by claude.ia from MPC561RM.pdf
//@category MPC5xx
//@keybinding
//@menupath
//@toolbar

import ghidra.app.script.GhidraScript;
import ghidra.program.model.address.Address;
import ghidra.program.model.symbol.SourceType;
import ghidra.program.model.symbol.Symbol;
import ghidra.program.model.symbol.SymbolTable;
import ghidra.program.model.data.*;
import ghidra.program.model.mem.MemoryBlock;

public class MPC561_RegisterMap extends GhidraScript {

    private DataTypeManager dtm;
    private SymbolTable symbolTable;

    @Override
    public void run() throws Exception {
        dtm = currentProgram.getDataTypeManager();
        symbolTable = currentProgram.getSymbolTable();

        println("MPC561/MPC563 Register Memory Map Script");
        println("=========================================");
        println("All registers prefixed with REG_");

        // Create BBC registers
        createBBCRegisters();

        // Create USIU registers
        createUSIURegisters();

        // Create UC3F Flash Control registers
        createUC3FRegisters();

        // Create DPTRAM registers
        createDPTRAMRegisters();

        // Create TPU3 A and B registers
        createTPU3Registers();

        // Create QADC64E A and B registers
        createQADCRegisters();

        // Create QSMCM registers
        createQSMCMRegisters();

        // Create PPM registers
        createPPMRegisters();

        // Create MIOS14 registers
        createMIOS14Registers();

        // Create TouCAN A, B, C registers with all message buffers
        createTouCANRegisters();

        // Create UIMB registers
        createUIMBRegisters();

        // Create CALRAM registers
        createCALRAMRegisters();

        println("Register mapping complete!");
    }

    private void createRegLabel(long address, String name, int size) throws Exception {
        Address addr = toAddr(address);
        String regName = "REG_" + name;

        // Remove any existing labels at this address
        Symbol[] existingSymbols = symbolTable.getSymbols(addr);
        for (Symbol sym : existingSymbols) {
            if (!sym.isPrimary() || sym.getSource() != SourceType.DEFAULT) {
                sym.delete();
            }
        }

        // Create the new label with REG_ prefix
        createLabel(addr, regName, true);

        // Apply appropriate data type based on size (using stdint types)
        String typeName = null;
        switch (size) {
            case 1: typeName = "/uint8_t"; break;
            case 2: typeName = "/uint16_t"; break;
            case 4: typeName = "/uint32_t"; break;
        }

        if (typeName != null) {
            DataType dt = dtm.getDataType(typeName);
            if (dt != null) {
                clearListing(addr, addr.add(size - 1));
                createData(addr, dt);
            }
        }
    }

    private void createBBCRegisters() throws Exception {
        println("Creating BBC (Burst Buffer Controller) registers...");

        // DCCR0-DCCR15 - Decompressor Class Configuration Registers
        for (int i = 0; i <= 15; i++) {
            createRegLabel(0x002FA000L + (i * 4), "DCCR" + i, 4);
        }
    }

    private void createUSIURegisters() throws Exception {
        println("Creating USIU (Unified System Interface Unit) registers...");

        // SIU Module Configuration
        createRegLabel(0x002FC000L, "SIUMCR", 4);
        createRegLabel(0x002FC004L, "SYPCR", 4);
        createRegLabel(0x002FC00EL, "SWSR", 2);
        createRegLabel(0x002FC010L, "SIPEND", 4);
        createRegLabel(0x002FC014L, "SIMASK", 4);
        createRegLabel(0x002FC018L, "SIEL", 4);
        createRegLabel(0x002FC01CL, "SIVEC", 4);
        createRegLabel(0x002FC020L, "TESR", 4);
        createRegLabel(0x002FC024L, "SGPIODT1", 4);
        createRegLabel(0x002FC028L, "SGPIODT2", 4);
        createRegLabel(0x002FC02CL, "SGPIOCR", 4);
        createRegLabel(0x002FC030L, "EMCR", 4);
        createRegLabel(0x002FC038L, "PDMCR2", 4);
        createRegLabel(0x002FC03CL, "PDMCR", 4);
        createRegLabel(0x002FC040L, "SIPEND2", 4);
        createRegLabel(0x002FC044L, "SIPEND3", 4);
        createRegLabel(0x002FC048L, "SIMASK2", 4);
        createRegLabel(0x002FC04CL, "SIMASK3", 4);
        createRegLabel(0x002FC050L, "SISR2", 4);
        createRegLabel(0x002FC054L, "SISR3", 4);

        // Memory Controller Registers
        createRegLabel(0x002FC100L, "BR0", 4);
        createRegLabel(0x002FC104L, "OR0", 4);
        createRegLabel(0x002FC108L, "BR1", 4);
        createRegLabel(0x002FC10CL, "OR1", 4);
        createRegLabel(0x002FC110L, "BR2", 4);
        createRegLabel(0x002FC114L, "OR2", 4);
        createRegLabel(0x002FC118L, "BR3", 4);
        createRegLabel(0x002FC11CL, "OR3", 4);
        createRegLabel(0x002FC140L, "DMBR", 4);
        createRegLabel(0x002FC144L, "DMOR", 4);
        createRegLabel(0x002FC178L, "MSTAT", 2);

        // System Integration Timers
        createRegLabel(0x002FC200L, "TBSCR", 2);
        createRegLabel(0x002FC204L, "TBREF0", 4);
        createRegLabel(0x002FC208L, "TBREF1", 4);
        createRegLabel(0x002FC220L, "RTCSC", 2);
        createRegLabel(0x002FC224L, "RTC", 4);
        createRegLabel(0x002FC228L, "RTSEC", 4);
        createRegLabel(0x002FC22CL, "RTCAL", 4);
        createRegLabel(0x002FC240L, "PISCR", 2);
        createRegLabel(0x002FC244L, "PITC", 4);
        createRegLabel(0x002FC248L, "PITR", 4);

        // Clocks and Reset
        createRegLabel(0x002FC280L, "SCCR", 4);
        createRegLabel(0x002FC284L, "PLPRCR", 4);
        createRegLabel(0x002FC288L, "RSR", 2);
        createRegLabel(0x002FC28CL, "COLIR", 2);
        createRegLabel(0x002FC290L, "VSRMCR", 2);

        // System Integration Timer Keys
        createRegLabel(0x002FC300L, "TBSCRK", 4);
        createRegLabel(0x002FC304L, "TBREF0K", 4);
        createRegLabel(0x002FC308L, "TBREF1K", 4);
        createRegLabel(0x002FC30CL, "TBK", 4);
        createRegLabel(0x002FC320L, "RTCSCK", 4);
        createRegLabel(0x002FC324L, "RTCK", 4);
        createRegLabel(0x002FC328L, "RTSECK", 4);
        createRegLabel(0x002FC32CL, "RTCALK", 4);
        createRegLabel(0x002FC340L, "PISCRIK", 4);
        createRegLabel(0x002FC344L, "PITCK", 4);

        // Clocks and Reset Keys
        createRegLabel(0x002FC380L, "SCCRK", 4);
        createRegLabel(0x002FC384L, "PLPRCRK", 4);
        createRegLabel(0x002FC388L, "RSRK", 4);

        // Test Register
        createRegLabel(0x002FC3FCL, "SIUTST", 4);
    }

    private void createUC3FRegisters() throws Exception {
        println("Creating UC3F Flash Control registers...");

        createRegLabel(0x002FC800L, "UC3FMCR", 4);
        createRegLabel(0x002FC804L, "UC3FMCRE", 4);
        createRegLabel(0x002FC808L, "UC3FCTL", 4);
    }

    private void createDPTRAMRegisters() throws Exception {
        println("Creating DPTRAM Control registers...");

        createRegLabel(0x00300000L, "DPTMCR", 2);
        createRegLabel(0x00300002L, "DPTTCR", 2);
        createRegLabel(0x00300004L, "RAMBAR", 2);
        createRegLabel(0x00300006L, "MISRH", 2);
        createRegLabel(0x00300008L, "MISRL", 2);
        createRegLabel(0x0030000AL, "MISCNT", 2);
    }

    private void createTPU3Registers() throws Exception {
        println("Creating TPU3 A and B registers...");

        // TPU3_A registers
        createRegLabel(0x00304000L, "TPUMCR_A", 2);
        createRegLabel(0x00304002L, "TCR_A", 2);
        createRegLabel(0x00304004L, "DSCR_A", 2);
        createRegLabel(0x00304006L, "DSSR_A", 2);
        createRegLabel(0x00304008L, "TICR_A", 2);
        createRegLabel(0x0030400AL, "CIER_A", 2);
        createRegLabel(0x0030400CL, "CFSR0_A", 2);
        createRegLabel(0x0030400EL, "CFSR1_A", 2);
        createRegLabel(0x00304010L, "CFSR2_A", 2);
        createRegLabel(0x00304012L, "CFSR3_A", 2);
        createRegLabel(0x00304014L, "HSQR0_A", 2);
        createRegLabel(0x00304016L, "HSQR1_A", 2);
        createRegLabel(0x00304018L, "HSRR0_A", 2);
        createRegLabel(0x0030401AL, "HSRR1_A", 2);
        createRegLabel(0x0030401CL, "CPR0_A", 2);
        createRegLabel(0x0030401EL, "CPR1_A", 2);
        createRegLabel(0x00304020L, "CISR_A", 2);
        createRegLabel(0x00304022L, "LR_A", 2);
        createRegLabel(0x00304024L, "SGLR_A", 2);
        createRegLabel(0x00304026L, "DCNR_A", 2);
        createRegLabel(0x00304028L, "TPUMCR2_A", 2);
        createRegLabel(0x0030402AL, "TPUMCR3_A", 2);
        createRegLabel(0x0030402CL, "ISDR_A", 2);
        createRegLabel(0x0030402EL, "ISCR_A", 2);

        // TPU3_A Channel Parameter Registers
        for (int ch = 0; ch <= 15; ch++) {
            long baseAddr = 0x00304100L + (ch * 0x10);
            createRegLabel(baseAddr, "TPU3A_CH" + ch + "_PARAM", 4);
        }

        // TPU3_B registers
        createRegLabel(0x00304400L, "TPUMCR_B", 2);
        createRegLabel(0x00304402L, "TCR_B", 2);
        createRegLabel(0x00304404L, "DSCR_B", 2);
        createRegLabel(0x00304406L, "DSSR_B", 2);
        createRegLabel(0x00304408L, "TICR_B", 2);
        createRegLabel(0x0030440AL, "CIER_B", 2);
        createRegLabel(0x0030440CL, "CFSR0_B", 2);
        createRegLabel(0x0030440EL, "CFSR1_B", 2);
        createRegLabel(0x00304410L, "CFSR2_B", 2);
        createRegLabel(0x00304412L, "CFSR3_B", 2);
        createRegLabel(0x00304414L, "HSQR0_B", 2);
        createRegLabel(0x00304416L, "HSQR1_B", 2);
        createRegLabel(0x00304418L, "HSRR0_B", 2);
        createRegLabel(0x0030441AL, "HSRR1_B", 2);
        createRegLabel(0x0030441CL, "CPR0_B", 2);
        createRegLabel(0x0030441EL, "CPR1_B", 2);
        createRegLabel(0x00304420L, "CISR_B", 2);
        createRegLabel(0x00304422L, "LR_B", 2);
        createRegLabel(0x00304424L, "SGLR_B", 2);
        createRegLabel(0x00304426L, "DCNR_B", 2);
        createRegLabel(0x00304428L, "TPUMCR2_B", 2);
        createRegLabel(0x0030442AL, "TPUMCR3_B", 2);
        createRegLabel(0x0030442CL, "ISDR_B", 2);
        createRegLabel(0x0030442EL, "ISCR_B", 2);

        // TPU3_B Channel Parameter Registers
        for (int ch = 0; ch <= 15; ch++) {
            long baseAddr = 0x00304500L + (ch * 0x10);
            createRegLabel(baseAddr, "TPU3B_CH" + ch + "_PARAM", 4);
        }
    }

    private void createQADCRegisters() throws Exception {
        println("Creating QADC64E A and B registers...");

        // QADC_A
        createRegLabel(0x00304800L, "QADC64MCR_A", 2);
        createRegLabel(0x00304802L, "QADC64TST_A", 2);
        createRegLabel(0x00304804L, "QADC64INT_A", 2);
        createRegLabel(0x00304806L, "PORTQA_A", 2);
        createRegLabel(0x00304808L, "DDRQA_A", 2);
        createRegLabel(0x0030480AL, "QACR0_A", 2);
        createRegLabel(0x0030480CL, "QACR1_A", 2);
        createRegLabel(0x0030480EL, "QACR2_A", 2);
        createRegLabel(0x00304810L, "QASR0_A", 2);
        createRegLabel(0x00304812L, "QASR1_A", 2);

        // QADC_A Conversion Command Word Table (64 entries)
        for (int i = 0; i < 64; i++) {
            createRegLabel(0x00304A00L + (i * 2), "QADCA_CCW" + i, 2);
        }

        // QADC_A Result Tables
        for (int i = 0; i < 64; i++) {
            createRegLabel(0x00304A80L + (i * 2), "QADCA_RJURR" + i, 2);
        }
        for (int i = 0; i < 64; i++) {
            createRegLabel(0x00304B00L + (i * 2), "QADCA_LJSRR" + i, 2);
        }
        for (int i = 0; i < 64; i++) {
            createRegLabel(0x00304B80L + (i * 2), "QADCA_LJURR" + i, 2);
        }

        // QADC_B
        createRegLabel(0x00304C00L, "QADC64MCR_B", 2);
        createRegLabel(0x00304C02L, "QADC64TST_B", 2);
        createRegLabel(0x00304C04L, "QADC64INT_B", 2);
        createRegLabel(0x00304C06L, "PORTQA_B", 2);
        createRegLabel(0x00304C08L, "DDRQA_B", 2);
        createRegLabel(0x00304C0AL, "QACR0_B", 2);
        createRegLabel(0x00304C0CL, "QACR1_B", 2);
        createRegLabel(0x00304C0EL, "QACR2_B", 2);
        createRegLabel(0x00304C10L, "QASR0_B", 2);
        createRegLabel(0x00304C12L, "QASR1_B", 2);

        // QADC_B Conversion Command Word Table
        for (int i = 0; i < 64; i++) {
            createRegLabel(0x00304E00L + (i * 2), "QADCB_CCW" + i, 2);
        }

        // QADC_B Result Tables
        for (int i = 0; i < 64; i++) {
            createRegLabel(0x00304E80L + (i * 2), "QADCB_RJURR" + i, 2);
        }
        for (int i = 0; i < 64; i++) {
            createRegLabel(0x00304F00L + (i * 2), "QADCB_LJSRR" + i, 2);
        }
        for (int i = 0; i < 64; i++) {
            createRegLabel(0x00304F80L + (i * 2), "QADCB_LJURR" + i, 2);
        }
    }

    private void createQSMCMRegisters() throws Exception {
        println("Creating QSMCM registers...");

        createRegLabel(0x00305000L, "QSMCMMCR", 2);
        createRegLabel(0x00305002L, "QTEST", 2);
        createRegLabel(0x00305004L, "QDSCI_IL", 2);
        createRegLabel(0x00305006L, "QSPI_IL", 2);
        createRegLabel(0x00305008L, "SCC1R0", 2);
        createRegLabel(0x0030500AL, "SCC1R1", 2);
        createRegLabel(0x0030500CL, "SC1SR", 2);
        createRegLabel(0x0030500EL, "SC1DR", 2);
        createRegLabel(0x00305014L, "PORTQS", 2);
        createRegLabel(0x00305016L, "PQSPAR", 2);
        createRegLabel(0x00305018L, "SPCR0", 2);
        createRegLabel(0x0030501AL, "SPCR1", 2);
        createRegLabel(0x0030501CL, "SPCR2", 2);
        createRegLabel(0x0030501EL, "SPCR3", 1);
        createRegLabel(0x0030501FL, "SPSR", 1);
        createRegLabel(0x00305020L, "SCC2R0", 2);
        createRegLabel(0x00305022L, "SCC2R1", 2);
        createRegLabel(0x00305024L, "SC2SR", 2);
        createRegLabel(0x00305026L, "SC2DR", 2);
        createRegLabel(0x00305028L, "QSCI1CR", 2);
        createRegLabel(0x0030502AL, "QSCI1SR", 2);

        // Transmit Queue (16 entries)
        for (int i = 0; i < 16; i++) {
            createRegLabel(0x0030502CL + (i * 2), "SCTQ" + i, 2);
        }

        // Receive Queue (16 entries)
        for (int i = 0; i < 16; i++) {
            createRegLabel(0x0030504CL + (i * 2), "SCRQ" + i, 2);
        }

        // QSPI Receive Data RAM (16 entries x 2 bytes)
        for (int i = 0; i < 16; i++) {
            createRegLabel(0x00305140L + (i * 2), "RECRAM" + i, 2);
        }

        // QSPI Transmit Data RAM (16 entries x 2 bytes)
        for (int i = 0; i < 16; i++) {
            createRegLabel(0x00305180L + (i * 2), "TRANRAM" + i, 2);
        }

        // QSPI Command RAM (16 entries x 1 byte)
        for (int i = 0; i < 16; i++) {
            createRegLabel(0x003051C0L + i, "COMDRAM" + i, 1);
        }
    }

    private void createPPMRegisters() throws Exception {
        println("Creating PPM registers...");

        createRegLabel(0x00305C00L, "PPMMCR", 2);
        createRegLabel(0x00305C04L, "PPMPCR", 2);
        createRegLabel(0x00305C06L, "TX_CONFIG_1", 2);
        createRegLabel(0x00305C08L, "TX_CONFIG_2", 2);
        createRegLabel(0x00305C0EL, "RX_CONFIG_1", 2);
        createRegLabel(0x00305C10L, "RX_CONFIG_2", 2);
        createRegLabel(0x00305C16L, "RX_DATA", 2);
        createRegLabel(0x00305C1AL, "RX_SHIFTER", 2);
        createRegLabel(0x00305C1EL, "TX_DATA", 2);
        createRegLabel(0x00305C22L, "GPDO", 2);
        createRegLabel(0x00305C24L, "GPDI", 2);
        createRegLabel(0x00305C26L, "SHORT_REG", 2);
        createRegLabel(0x00305C28L, "SHORT_CH_REG", 2);
        createRegLabel(0x00305C2AL, "SCALE_TCLK_REG", 2);
    }

    private void createMIOS14Registers() throws Exception {
        println("Creating MIOS14 registers...");

        // MPWMSM0-5 (PWM Submodules 0-5)
        for (int i = 0; i <= 5; i++) {
            long base = 0x00306000L + (i * 8);
            createRegLabel(base + 0, "MPWMSM" + i + "_PERR", 2);
            createRegLabel(base + 2, "MPWMSM" + i + "_PULR", 2);
            createRegLabel(base + 4, "MPWMSM" + i + "_CNTR", 2);
            createRegLabel(base + 6, "MPWMSM" + i + "_SCR", 2);
        }

        // MMCSM6-8 (Modulus Counter Submodules 6-8)
        createRegLabel(0x00306030L, "MMCSM6_CNT", 2);
        createRegLabel(0x00306032L, "MMCSM6_ML", 2);
        createRegLabel(0x00306034L, "MMCSM6_SCRD", 2);
        createRegLabel(0x00306036L, "MMCSM6_SCR", 2);

        createRegLabel(0x00306038L, "MMCSM7_CNT", 2);
        createRegLabel(0x0030603AL, "MMCSM7_ML", 2);
        createRegLabel(0x0030603EL, "MMCSM7_SCR", 2);

        createRegLabel(0x00306040L, "MMCSM8_CNT", 2);
        createRegLabel(0x00306042L, "MMCSM8_ML", 2);
        createRegLabel(0x00306046L, "MMCSM8_SCR", 2);

        // MDASM11-15 (Double Action Submodules 11-15)
        int[] dasmChannels = {11, 12, 13, 14, 15};
        long[] dasmBases = {0x00306058L, 0x00306060L, 0x00306068L, 0x00306070L, 0x00306078L};
        for (int i = 0; i < dasmChannels.length; i++) {
            createRegLabel(dasmBases[i] + 0, "MDASM" + dasmChannels[i] + "_AR", 2);
            createRegLabel(dasmBases[i] + 2, "MDASM" + dasmChannels[i] + "_BR", 2);
            createRegLabel(dasmBases[i] + 6, "MDASM" + dasmChannels[i] + "_SCR", 2);
        }

        // MPWMSM16-21 (PWM Submodules 16-21)
        for (int i = 16; i <= 21; i++) {
            long base = 0x00306080L + ((i - 16) * 8);
            createRegLabel(base + 0, "MPWMSM" + i + "_PERR", 2);
            createRegLabel(base + 2, "MPWMSM" + i + "_PULR", 2);
            createRegLabel(base + 4, "MPWMSM" + i + "_CNTR", 2);
            createRegLabel(base + 6, "MPWMSM" + i + "_SCR", 2);
        }

        // MMCSM22-24 (Modulus Counter Submodules 22-24)
        createRegLabel(0x003060B0L, "MMCSM22_CNT", 2);
        createRegLabel(0x003060B2L, "MMCSM22_ML", 2);
        createRegLabel(0x003060B6L, "MMCSM22_SCR", 2);

        createRegLabel(0x003060B8L, "MMCSM23_CNT", 2);
        createRegLabel(0x003060BAL, "MMCSM23_ML", 2);
        createRegLabel(0x003060BEL, "MMCSM23_SCR", 2);

        createRegLabel(0x003060C0L, "MMCSM24_CNT", 2);
        createRegLabel(0x003060C2L, "MMCSM24_ML", 2);
        createRegLabel(0x003060C6L, "MMCSM24_SCR", 2);

        // MDASM27-31 (Double Action Submodules 27-31)
        int[] dasmChannels2 = {27, 28, 29, 30, 31};
        long[] dasmBases2 = {0x003060D8L, 0x003060E0L, 0x003060E8L, 0x003060F0L, 0x003060F8L};
        for (int i = 0; i < dasmChannels2.length; i++) {
            createRegLabel(dasmBases2[i] + 0, "MDASM" + dasmChannels2[i] + "_AR", 2);
            createRegLabel(dasmBases2[i] + 2, "MDASM" + dasmChannels2[i] + "_BR", 2);
            createRegLabel(dasmBases2[i] + 6, "MDASM" + dasmChannels2[i] + "_SCR", 2);
        }

        // MPIOSM (Parallel Port I/O Submodule)
        createRegLabel(0x00306100L, "MPIOSMDR", 2);
        createRegLabel(0x00306102L, "MPIOSMDDR", 2);

        // MBISM (Bus Interface Submodule)
        createRegLabel(0x00306800L, "MIOS14TPCR", 2);
        createRegLabel(0x00306802L, "MIOS14VECT", 2);
        createRegLabel(0x00306804L, "MIOS14VNR", 2);
        createRegLabel(0x00306806L, "MIOS14MCR", 2);

        // MCPSM (Counter/Prescaler Status/Control)
        createRegLabel(0x00306816L, "MCPSMSCR", 2);

        // MIRSM0 (Interrupt Status Submodule 0)
        createRegLabel(0x00306C00L, "MIOS14SR0", 2);
        createRegLabel(0x00306C04L, "MIOS14ER0", 2);
        createRegLabel(0x00306C06L, "MIOS14RPR0", 2);

        // MIRSM1 (Interrupt Status Submodule 1)
        createRegLabel(0x00306C40L, "MIOS14SR1", 2);
        createRegLabel(0x00306C44L, "MIOS14ER1", 2);
        createRegLabel(0x00306C46L, "MIOS14RPR1", 2);

        // MBISM Interrupt Level Registers
        createRegLabel(0x00306C30L, "MIOS14LVL0", 2);
        createRegLabel(0x00306C70L, "MIOS14LVL1", 2);
    }

    private void createTouCANRegisters() throws Exception {
        println("Creating TouCAN A, B, C registers with all message buffers...");

        // TouCAN_A
        createTouCANModule("A", 0x00307080L, 0x00307100L);

        // TouCAN_B
        createTouCANModule("B", 0x00307480L, 0x00307500L);

        // TouCAN_C
        createTouCANModule("C", 0x00307880L, 0x00307900L);
    }

    private void createTouCANModule(String suffix, long ctrlBase, long mbuffBase) throws Exception {
        // Control registers
        createRegLabel(ctrlBase + 0x00, "CANMCR_" + suffix, 2);
        createRegLabel(ctrlBase + 0x02, "CANTCR_" + suffix, 2);
        createRegLabel(ctrlBase + 0x04, "CANICR_" + suffix, 2);
        createRegLabel(ctrlBase + 0x06, "CANCTRL0_" + suffix, 1);
        createRegLabel(ctrlBase + 0x07, "CANCTRL1_" + suffix, 1);
        createRegLabel(ctrlBase + 0x08, "PRESDIV_" + suffix, 1);
        createRegLabel(ctrlBase + 0x09, "CTRL2_" + suffix, 1);
        createRegLabel(ctrlBase + 0x0A, "TIMER_" + suffix, 2);
        createRegLabel(ctrlBase + 0x10, "RXGMSKHI_" + suffix, 2);
        createRegLabel(ctrlBase + 0x12, "RXGMSKLO_" + suffix, 2);
        createRegLabel(ctrlBase + 0x14, "RX14MSKHI_" + suffix, 2);
        createRegLabel(ctrlBase + 0x16, "RX14MSKLO_" + suffix, 2);
        createRegLabel(ctrlBase + 0x18, "RX15MSKHI_" + suffix, 2);
        createRegLabel(ctrlBase + 0x1A, "RX15MSKLO_" + suffix, 2);
        createRegLabel(ctrlBase + 0x20, "ESTAT_" + suffix, 2);
        createRegLabel(ctrlBase + 0x22, "IMASK_" + suffix, 2);
        createRegLabel(ctrlBase + 0x24, "IFLAG_" + suffix, 2);
        createRegLabel(ctrlBase + 0x26, "RXECTR_" + suffix, 1);
        createRegLabel(ctrlBase + 0x27, "TXECTR_" + suffix, 1);

        // Message Buffers 0-15 (16 bytes each)
        // Each message buffer structure:
        // Offset 0x00: Control/Status (2 bytes)
        // Offset 0x02: ID High (2 bytes)
        // Offset 0x04: ID Low (2 bytes)
        // Offset 0x06: Data bytes 0-1 (2 bytes)
        // Offset 0x08: Data bytes 2-3 (2 bytes)
        // Offset 0x0A: Data bytes 4-5 (2 bytes)
        // Offset 0x0C: Data bytes 6-7 (2 bytes)
        // Offset 0x0E: Reserved (2 bytes)

        for (int buf = 0; buf <= 15; buf++) {
            long bufBase = mbuffBase + (buf * 0x10);
            createRegLabel(bufBase + 0x00, "CAN" + suffix + "_MB" + buf + "_CS", 2);
            createRegLabel(bufBase + 0x02, "CAN" + suffix + "_MB" + buf + "_ID_HI", 2);
            createRegLabel(bufBase + 0x04, "CAN" + suffix + "_MB" + buf + "_ID_LO", 2);
            createRegLabel(bufBase + 0x06, "CAN" + suffix + "_MB" + buf + "_DATA0", 2);
            createRegLabel(bufBase + 0x08, "CAN" + suffix + "_MB" + buf + "_DATA2", 2);
            createRegLabel(bufBase + 0x0A, "CAN" + suffix + "_MB" + buf + "_DATA4", 2);
            createRegLabel(bufBase + 0x0C, "CAN" + suffix + "_MB" + buf + "_DATA6", 2);
        }
    }

    private void createUIMBRegisters() throws Exception {
        println("Creating UIMB registers...");

        createRegLabel(0x00307F80L, "UMCR", 4);
        createRegLabel(0x00307F90L, "UTSTCREG", 4);
        createRegLabel(0x00307FA0L, "UIPEND", 4);
    }

    private void createCALRAMRegisters() throws Exception {
        println("Creating CALRAM Control registers...");

        createRegLabel(0x00380000L, "CRAMMCR", 4);
        createRegLabel(0x00380004L, "CRAMTST", 4);
        createRegLabel(0x00380008L, "CRAM_RBA0", 4);
        createRegLabel(0x0038000CL, "CRAM_RBA1", 4);
        createRegLabel(0x00380010L, "CRAM_RBA2", 4);
        createRegLabel(0x00380014L, "CRAM_RBA3", 4);
        createRegLabel(0x00380018L, "CRAM_RBA4", 4);
        createRegLabel(0x0038001CL, "CRAM_RBA5", 4);
        createRegLabel(0x00380020L, "CRAM_RBA6", 4);
        createRegLabel(0x00380024L, "CRAM_RBA7", 4);
        createRegLabel(0x00380028L, "CRAM_OLVCR", 4);
        createRegLabel(0x0038002CL, "READI_OTR", 4);
    }
}
