<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<roms>
 <rom base="T4E090_NOMODEL">
  <romid>
   <xmlid>F121E0010H</xmlid>
   <market>FED</market>
   <model>Elise</model>
   <internalidaddress>0x3656</internalidaddress>
   <internalidstring>F121E0010H</internalidstring>
  </romid>
 </rom>
 <rom base="T4E090_NOMODEL">
  <romid>
   <xmlid>D129E6004H</xmlid>
   <market>FED</market>
   <model>Exige</model>
   <internalidaddress>0x3656</internalidaddress>
   <internalidstring>D129E6004H</internalidstring>
  </romid>
 </rom>
 <rom base="T4E090_NOMODEL">
  <romid>
   <xmlid>D120E0030H</xmlid>
   <market>ROW</market>
   <model>Elise</model>
   <internalidaddress>0x3656</internalidaddress>
   <internalidstring>D120E0030H</internalidstring>
  </romid>
 </rom>
 <rom base="T4E090_NOMODEL">
  <romid>
   <xmlid>C128E6010H</xmlid>
   <market>ROW</market>
   <model>Exige</model>
   <internalidaddress>0x3656</internalidaddress>
   <internalidstring>C128E6010H</internalidstring>
  </romid>
 </rom>
 <rom base="T4E090">
  <romid>
   <xmlid>T4E090_NOMODEL</xmlid>
   <submodel>2006-2007</submodel>
   <filesize>15508b</filesize>
  </romid>
  <table name="ecu: unlock magic" storageaddress="0x3C8E"/>
  <table name="ecu: CRC stored" storageaddress="0x3C92"/>
 </rom>
</roms>