  <romid>
   <xmlid>XTRACAL3</xmlid>
   <market>World</market>
   <make>Lotus</make>
   <model>Elise/Exige Patched</model>
   <submodel>2008-2011</submodel>
   <transmission>MT</transmission>
   <filesize>64kb</filesize>
   <memmodel>MPC563</memmodel>
   <flashmethod>CRP</flashmethod>
   <internalidaddress>{CAL_extra}</internalidaddress>
   <internalidstring>XTRACAL3</internalidstring>
   <noRamOffset>1</noRamOffset>
  </romid>

